### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'typeDict'

### ISSUE THREAD

**Issue by tshanableh** [AraMambreyan/Improved-Dense-Trajectories#1]
Greetings:

Many thanks for sharing the code.
I ran it on Windows, followed the steps you listed and got the following error, any tips ?

Traceback (most recent call last):
  File "run_idt.py", line 4, in <module>
    from sklearn.mixture import GaussianMixture as GMM
  File "/usr/local/lib/python3.8/dist-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/__init__.py", line 17, in <module>
    from scipy.sparse import issparse
  File "/usr/lib/python3/dist-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/usr/lib/python3/dist-packages/scipy/sparse/base.py", line 8, in <module>
    from .sputils import (isdense, isscalarlike, isintlike,
  File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <module>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <listcomp>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'

**Comment by AraMambreyan** [comment]
Hello,

Yes, sounds like a version issue. See this [thread](https://stackoverflow.com/questions/74852225/attributeerror-module-numpy-has-no-attribute-typedict). 

I should have used versions in the [Dockerfile](https://github.com/AraMambreyan/Improved-Dense-Trajectories/blob/master/Dockerfile). Line 72 `pip3 install --upgrade numpy` installs the latest version of numpy. So if you replace it with `pip3 install numpy==1.21` as the thread linked above suggests it should probably work.

If it does, please feel free to make a PR.

**Comment by tshanableh** [comment]
Your solution worked, many thanks indeed!

**Comment by AraMambreyan** [comment]
Glad it helped!
